// ==============================================
// Copyright 2004 by CodeLifter.com
// Free for all; but please leave in this header.
// ==============================================

var Quotation=new Array() // do not change this!

// Set up the quotations to be shown, below.
// To add more quotations, continue with the
// pattern, adding to the array.  Remember
// to increment the Quotation[x] index!

Quotation[0] = "I love playing at Solaria because every member is able to contribute to the overall plot and make a difference. Everyone works together to make a great story and no one player is more important than another - we always support each other!<br/> <font size='2'>- Kitya</font>";
Quotation[1] = "I love playing an assistant weyrlingmaster because there's always so many opportunities for threads! My character is actively involved in shaping the future of the Weyr, and running lessons is so much fun. Since my weyrlingmaster is also female, she's also uniquely positioned to support new female riders in their own struggle to be accepted by a male-dominated hierarchy.<br/><font size='2'>- Kitya, player of Assistant Weyrlingmaster Cevida of green Vetianth</font>";
Quotation[2] = "I love playing brownriders because they can push at the boundaries of rank; they\'re not bronze, but a good brown is almost as good and can even catch a queen in flight. They have enough rank to be able to hope for a Wingsecond or even Wingleader position, but they have to work hard for it and that makes for great RP.<br/><font size='2'>- Kitya, player of S\'wyn of brown Neovith and M\'tain of brown Castilath</font>";
Quotation[3] = "I love playing at Solaria Weyr because I can work out and play long-term plots, both personally for my own characters\' story lines and for the whole site\'s story line. I also love how many opportunities there are for members to be involved in running the site and I feel that that gives everyone a real sense of ownership. From IC and OOC member groups like Wingleader Team, Weyrling Team, Summary Team, and Wiki Wizards, plus our Search Committee for running hatchings. There\'s so much to do! Plus any major decisions that would impact the site rules, the canon and story, and the characters is decided by majority vote of all members. <br/><font size='2'>- Shouriko</font>";
Quotation[4] = "I love playing women Crafters because there\'s so much room for growth in the story and there\'s available conflict for the characters. Your character is fighting for respect in their chosen field and the right to earn their Journeyman knots with twice as much effort and passion as the men. There\'s no women Masters yet, and the chance to play as if your character is aiming for that lofty goal is kind of exciting! <br/><font size='2'>- Shouriko, player of Journeyman Farmer Sveta</font>";
Quotation[5] = "I love playing child and adolescent characters because these are the characters who will change the most while you play them. You can plan for them to walk down one life path and develop into a certain personality, but maybe as you encounter other characters and they make choices in random open threads those plans can change. It can be completely unexpected! It\'s so neat to start out with a young character and over the span of their coming into adulthood find them turning into a completely different person than you might have expected.<br/><font size='2'>-Shouriko, player of Ketrin\'s Lord Holder heir Renaire (created at 6); infirmary/dragon aide Feyon (created at 8); Weyrwoman Phyrra rider of gold Femaith (created at 12)</font>";
Quotation[6] = "Solaria is an awesome site, and the \'ranking\' characters are given to anyone, even if they don\'t necessarily ask for it. N\'din, my wonderful bronzerider, was an adopted character. During the Senior Weyrwoman\'s flight I threw him in, because according to his character sheet he always encourages Vesuvath to fly the Golds, and I was picked as the winner. I was shocked, and happy. I had never intended to have N\'din as Weyrleader, I had even disparaged him in our chat box, but love having a Weyrleader now, and it\'s all thanks to the site vote. I have been able to institute several plots that affected the Weyr as a whole, and have had admin support the whole way through. Women\'s Wing version 2, that was all me (and N\'din) and it is AWESOME! I can not recommend this site enough just for this one reason, \'ranking\' characters are NOT limited to admins, and the power that they have is given completely to the player running the character. The \'ranking\' characters in the Weyr are decided by vote, of all the players, and it\'s just AMAZING! <br/><font size='2'>- WunderingMind, player of Weyrleader N\'din, rider of bronze Vesuvath</font>";
Quotation[7] = "Solaria is an amazing site, really and totally amazing. You can choose to create a character, or you can adopt one that was given up (for whatever reason). One of the characters that I adopted is Harla of blue Flarroth, yes a female dragonrider on a blue dragon. This is considered a \'special\' character type, but I was still allowed to adopt her fairly early into my play time here on Solaria. She\'s an amazing fireball of a character, and one of the more vocal proponents of women on fighting dragons, and their equal treatment. One of the most amazing things about adopting a character, like Harla, is that she came with a full profile already. With very little work Harla was updated, tweaked a bit to fit my play style, and ready to go. She came with art, a play by, a firelizard, and IC connections already. There were no issues about me, as a new player on the site, picking up Harla as a special character, and it has been an amazing ride since then.<br/><font size='2'>- WunderingMind, player of Harla, rider of blue Flarroth</font>";
Quotation[8] = "Solaria has been one of the most accepting sites I have ever joined and allowed me a lot of rp experience.  Playing a female Journeyman Healer in a \"man\'s\" world has given me so much room for rp drama and growth.  Playing out the struggle a woman faced on Pern has helped me create a more rounded character. <br/><font size='2'>- Sickwater,player of Journeyman Evarrel</font>";
Quotation[9] = "Coming to Solaria was a hard choice for me because I had rp\'d on so many sites and been excluded, but Solaria accepted me with such enthusiasm. I have been encouraged, built up, and taught to be a better writer. The best part is not once did they make me feel small or excluded. My plots have been accepted with open arms and played enthusiastically and I feel like I am more than just another player I am a real member of Solaria\'s family. I am a new member but already I feel like I\'ve been here forever. <br/><font size='2'>- Sickwater</font>";
Quotation[10] = "Talora was pretty much my first character, and immediately she had a ton of topics and plots. She has such a big family it really made it easy to get going with this site. Now she has a lot of friends, a crush, two flits, and is standing for her chance at a gold. I have no idea where she\'ll end up, but that\'s the fun and magic of this site. You just never know what you\'ll get. <br/><font size='2'>- Kati, player of baker/candidate Talora</font>";
Quotation[11] = "I came to Solaria after many years of being away from roleplaying and I still can\'t believe how friendly everyone is! From the first minute I joined, everyone made an effort to ensure that I felt included both OOC and IC, answering questions and helping me gain a foothold in the established lore. I\'ve never once felt uncomfortable or unwelcome here and the numerous site-wide plots and events made it especially easy to jump in with a new character. Solaria really is a group of the friendliest, most phenomenal writers I\'ve ever met! <br/><font size='2'>- Shelacula</font>";
Quotation[12] = "Even as a new player, I was able to adopt from the most recent PC clutch. I picked up J\'er, and have already fallen in love with getting him and his weirdo dragon into trouble! <br/><font size='2'>- Michi, player of Weyrling J\'er of Green Juleeth</font>";
Quotation[13] = "I love playing at Solaria Weyr for so many reasons. First, there\'s the built-in IC drama of social change, with women struggling to obtain respect in a society dismissive of them, and the long history of Weyr-Hold tensions. Then there\'s the democratic approach to how the site runs; major decisions are put to a site vote and there are annual site discussions where everyone can have a say in how the site is run. And finally, there are the people. The members of Solaria are such a lovely and supportive bunch, welcoming of plots both big and small. From day one it has never been difficult to find RP or get my characters involved. All this and so much more, that\'s why I love Solaria! <br/><font size='2'>- Corgi</font>";
Quotation[14] = "Solaria Weyr is a great place to be, I joined it because it was a long running game, plenty of active players, fantastic and friendly admins and a color scheme that\'s easy on the eyes. I really like how PC Hatchings are done, it works really well and never boring. I would definitely recommend Solaria Weyr to anybody interested in a more Canon based Dragonriders of Pern game. <br/><font size='2'>- LdyPayne</font>";
// ======================================
// Do not change anything below this line
// ======================================
var Q = Quotation.length;
var whichQuotation=Math.round(Math.random()*(Q-1));
function showQuotation(){document.write(Quotation[whichQuotation]);}
showQuotation();
